// Generated by gencpp from file serial_comm/pan_data.msg
// DO NOT EDIT!


#ifndef SERIAL_COMM_MESSAGE_PAN_DATA_H
#define SERIAL_COMM_MESSAGE_PAN_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial_comm
{
template <class ContainerAllocator>
struct pan_data_
{
  typedef pan_data_<ContainerAllocator> Type;

  pan_data_()
    : yaw(0.0)
    , pitch(0.0)  {
    }
  pan_data_(const ContainerAllocator& _alloc)
    : yaw(0.0)
    , pitch(0.0)  {
  (void)_alloc;
    }



   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _pitch_type;
  _pitch_type pitch;




  typedef boost::shared_ptr< ::serial_comm::pan_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_comm::pan_data_<ContainerAllocator> const> ConstPtr;

}; // struct pan_data_

typedef ::serial_comm::pan_data_<std::allocator<void> > pan_data;

typedef boost::shared_ptr< ::serial_comm::pan_data > pan_dataPtr;
typedef boost::shared_ptr< ::serial_comm::pan_data const> pan_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_comm::pan_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_comm::pan_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace serial_comm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'serial_comm': ['/home/ssj/ros_ws/src/serial_comm/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::serial_comm::pan_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_comm::pan_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_comm::pan_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_comm::pan_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_comm::pan_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_comm::pan_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_comm::pan_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "84eddaf18b6b9df47b605419a0572436";
  }

  static const char* value(const ::serial_comm::pan_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x84eddaf18b6b9df4ULL;
  static const uint64_t static_value2 = 0x7b605419a0572436ULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_comm::pan_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_comm/pan_data";
  }

  static const char* value(const ::serial_comm::pan_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_comm::pan_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 yaw\n\
float64 pitch\n\
";
  }

  static const char* value(const ::serial_comm::pan_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_comm::pan_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.yaw);
      stream.next(m.pitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pan_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_comm::pan_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_comm::pan_data_<ContainerAllocator>& v)
  {
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_COMM_MESSAGE_PAN_DATA_H
