## *********************************************************
## 
## File autogenerated for the naoqimicrophone package 
## by the dynamic_reconfigure package.
## Please do not edit.
## 
## ********************************************************/

from dynamic_reconfigure.encoding import extract_params

inf = float('inf')

config_description = {'upper': 'DEFAULT', 'lower': 'groups', 'srcline': 246, 'name': 'Default', 'parent': 0, 'srcfile': '/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py', 'cstate': 'true', 'parentname': 'Default', 'class': 'DEFAULT', 'field': 'default', 'state': True, 'parentclass': '', 'groups': [], 'parameters': [{'srcline': 293, 'description': 'Camera speed (frames per second).', 'max': 30.0, 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py', 'name': 'frame_rate', 'edit_method': '', 'default': 15.0, 'level': 3, 'min': 1.0, 'type': 'double'}, {'srcline': 293, 'description': 'Audio sampling frequency.', 'max': 2147483647, 'cconsttype': 'const int', 'ctype': 'int', 'srcfile': '/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py', 'name': 'frequency', 'edit_method': "{'enum_description': 'Possible values for audio sampling frequency', 'enum': [{'srcline': 42, 'description': '', 'srcfile': '/home/ssj/ros_ws/src/naoqi_bridge/naoqi_sensors_py/cfg/NaoqiMicrophone.cfg', 'cconsttype': 'const int', 'value': 16000, 'ctype': 'int', 'type': 'int', 'name': 'SlowRate'}, {'srcline': 43, 'description': '', 'srcfile': '/home/ssj/ros_ws/src/naoqi_bridge/naoqi_sensors_py/cfg/NaoqiMicrophone.cfg', 'cconsttype': 'const int', 'value': 48000, 'ctype': 'int', 'type': 'int', 'name': 'HighRate'}]}", 'default': 16000, 'level': 3, 'min': -2147483648, 'type': 'int'}, {'srcline': 293, 'description': 'Timestamp Image and CameraInfo using ros::Time::now() instead of NAOqi timestamps', 'max': True, 'cconsttype': 'const bool', 'ctype': 'bool', 'srcfile': '/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py', 'name': 'use_ros_time', 'edit_method': '', 'default': True, 'level': 3, 'min': False, 'type': 'bool'}], 'type': '', 'id': 0}

min = {}
max = {}
defaults = {}
level = {}
type = {}
all_level = 0

#def extract_params(config):
#    params = []
#    params.extend(config['parameters'])    
#    for group in config['groups']:
#        params.extend(extract_params(group))
#    return params

for param in extract_params(config_description):
    min[param['name']] = param['min']
    max[param['name']] = param['max']
    defaults[param['name']] = param['default']
    level[param['name']] = param['level']
    type[param['name']] = param['type']
    all_level = all_level | param['level']

NaoqiMicrophone_SlowRate = 16000
NaoqiMicrophone_HighRate = 48000
