// Generated by gencpp from file pal_wifi_localization_msgs/GetWifiMap.msg
// DO NOT EDIT!


#ifndef PAL_WIFI_LOCALIZATION_MSGS_MESSAGE_GETWIFIMAP_H
#define PAL_WIFI_LOCALIZATION_MSGS_MESSAGE_GETWIFIMAP_H

#include <ros/service_traits.h>


#include <pal_wifi_localization_msgs/GetWifiMapRequest.h>
#include <pal_wifi_localization_msgs/GetWifiMapResponse.h>


namespace pal_wifi_localization_msgs
{

struct GetWifiMap
{

typedef GetWifiMapRequest Request;
typedef GetWifiMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetWifiMap
} // namespace pal_wifi_localization_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pal_wifi_localization_msgs::GetWifiMap > {
  static const char* value()
  {
    return "4273c0e2a4f41c0c71c07a4fee60fcee";
  }

  static const char* value(const ::pal_wifi_localization_msgs::GetWifiMap&) { return value(); }
};

template<>
struct DataType< ::pal_wifi_localization_msgs::GetWifiMap > {
  static const char* value()
  {
    return "pal_wifi_localization_msgs/GetWifiMap";
  }

  static const char* value(const ::pal_wifi_localization_msgs::GetWifiMap&) { return value(); }
};


// service_traits::MD5Sum< ::pal_wifi_localization_msgs::GetWifiMapRequest> should match 
// service_traits::MD5Sum< ::pal_wifi_localization_msgs::GetWifiMap > 
template<>
struct MD5Sum< ::pal_wifi_localization_msgs::GetWifiMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pal_wifi_localization_msgs::GetWifiMap >::value();
  }
  static const char* value(const ::pal_wifi_localization_msgs::GetWifiMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_wifi_localization_msgs::GetWifiMapRequest> should match 
// service_traits::DataType< ::pal_wifi_localization_msgs::GetWifiMap > 
template<>
struct DataType< ::pal_wifi_localization_msgs::GetWifiMapRequest>
{
  static const char* value()
  {
    return DataType< ::pal_wifi_localization_msgs::GetWifiMap >::value();
  }
  static const char* value(const ::pal_wifi_localization_msgs::GetWifiMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pal_wifi_localization_msgs::GetWifiMapResponse> should match 
// service_traits::MD5Sum< ::pal_wifi_localization_msgs::GetWifiMap > 
template<>
struct MD5Sum< ::pal_wifi_localization_msgs::GetWifiMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pal_wifi_localization_msgs::GetWifiMap >::value();
  }
  static const char* value(const ::pal_wifi_localization_msgs::GetWifiMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_wifi_localization_msgs::GetWifiMapResponse> should match 
// service_traits::DataType< ::pal_wifi_localization_msgs::GetWifiMap > 
template<>
struct DataType< ::pal_wifi_localization_msgs::GetWifiMapResponse>
{
  static const char* value()
  {
    return DataType< ::pal_wifi_localization_msgs::GetWifiMap >::value();
  }
  static const char* value(const ::pal_wifi_localization_msgs::GetWifiMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PAL_WIFI_LOCALIZATION_MSGS_MESSAGE_GETWIFIMAP_H
